"""Forecast model for storing Prophet forecast results."""

import uuid
from datetime import datetime

from sqlalchemy import Float, ForeignKey, Index, Integer
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database import Base


class Forecast(Base):
    """Forecast model for storing Prophet forecast results.

    Stores weekly demand forecasts generated by the Prophet model,
    including point estimates and confidence intervals.

    Attributes:
        id: Unique identifier (UUID)
        sku_id: Foreign key to the product
        warehouse_id: Optional warehouse filter used for forecast
        forecast_date: The date being forecasted
        yhat: Point forecast (predicted demand)
        yhat_lower: Lower bound of prediction interval
        yhat_upper: Upper bound of prediction interval
        interval_width: Width of prediction interval (0.80 or 0.95)
        model_trained_at: When the model was trained
        training_data_start: Start date of training data
        training_data_end: End date of training data
        training_data_points: Number of data points used for training
        mape: Model MAPE from cross-validation (if available)
        created_at: Timestamp when the record was created
    """

    __tablename__ = "forecasts"
    __table_args__ = (
        Index(
            "idx_forecasts_sku_date",
            "sku_id",
            "forecast_date",
        ),
        Index(
            "idx_forecasts_model_trained",
            "model_trained_at",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    sku_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("products.id", ondelete="CASCADE"),
        nullable=False,
    )
    warehouse_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("warehouses.id", ondelete="SET NULL"),
        nullable=True,
    )
    forecast_date: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
    )
    yhat: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )
    yhat_lower: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )
    yhat_upper: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )
    interval_width: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.80,
    )
    model_trained_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
    )
    training_data_start: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
    )
    training_data_end: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
    )
    training_data_points: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )
    mape: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        default=datetime.utcnow,
        nullable=False,
    )

    # Relationships
    product = relationship("Product", backref="forecasts")
    warehouse = relationship("Warehouse", backref="forecasts")

    def __repr__(self) -> str:
        return (
            f"<Forecast(sku_id={self.sku_id!r}, "
            f"forecast_date={self.forecast_date!r}, "
            f"yhat={self.yhat!r})>"
        )
